version: '3.2'

services:
  app:
    image: 'mechamonkey22/docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://0.0.0.0:5432/pokedex
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 8080
    ports:
      - 8080:8080

  db:
    restart: always
    image: 'postgres:13.1-alpine'
    container_name: db
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=pokedex